(()=>{const D=window.PORTFOLIO_DATA;const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
const disciplineDetails={
software:{subtitle:'End-to-end web applications',symbol:'</>',stats:[['65','API endpoints'],['05','featured systems']],stack:[['Python','Primary language'],['Java','Application logic'],['Flask','API services'],['Angular 17','Web interfaces'],['SQL','Data modelling'],['REST APIs','System boundaries']],projects:['openshield','breachlens','threatvault']},
cloud:{subtitle:'Infrastructure and repeatable delivery',symbol:'☁',stats:[['19','Azure workflows'],['CI','delivery gates']],stack:[['Azure','Cloud platform'],['Docker','Portable runtime'],['Linux','Host systems'],['GitHub Actions','Automated delivery'],['Key Vault','Secret control'],['PostgreSQL','Durable data']],projects:['openshield','dusk','threatvault']},
security:{subtitle:'Detection, evaluation and safe enforcement',symbol:'◇',stats:[['OWASP','maintainer'],['SIE','published integration']],stack:[['MITRE ATLAS','AI threat mapping'],['Zeek','Network evidence'],['River ML','Online detection'],['Ollama','Private inference'],['Python','Security tooling'],['k-anonymity','Privacy control']],projects:['openshield','dusk','iotsentinel','breachlens']},
quality:{subtitle:'Testable systems and explicit failure controls',symbol:'✓',stats:[['1,263','IoTSentinel tests'],['889','BreachLens tests']],stack:[['Automated tests','Regression evidence'],['API contracts','Stable boundaries'],['CI gates','Delivery checks'],['Benchmarks','Scoped measures'],['Recovery paths','Failure control'],['Code review','Shared quality']],projects:['openshield','dusk','iotsentinel','breachlens']}
};
const expertiseIcons={
  Python:'python',Java:'java',Flask:'flask','Angular 17':'angular',SQL:'sql','REST APIs':'rest',
  Azure:'azure',Docker:'docker',Linux:'linux','GitHub Actions':'github-actions','Key Vault':'key-vault',PostgreSQL:'postgresql',
  Zeek:'zeek','River ML':'river-ml',Ollama:'linux','MITRE ATLAS':'rest','k-anonymity':'key-vault',
  'Automated tests':'cicd','API contracts':'rest','CI gates':'github-actions',Benchmarks:'sql','Recovery paths':'linux','Code review':'github-actions'
};
const disciplineIcons={software:'disciplines',cloud:'tools',security:'maintainer',quality:'evidence'};
const renderExpertise=k=>{const x=D.expertise[k],detail=disciplineDetails[k];q('#expertise-panel').innerHTML=`<div class="discipline-top"><div class="discipline-title"><span class="discipline-symbol" aria-hidden="true"><img src="assets/ui-icons/${disciplineIcons[k]}.svg" alt=""></span><div><h3>${x.title}</h3><p class="meta">${detail.subtitle}</p></div></div><div class="discipline-stats">${detail.stats.map(([value,label])=>`<div><strong>${value}</strong><span>${label}</span></div>`).join('')}</div></div><p class="discipline-description">${x.description}</p><h4 class="discipline-label">Tools &amp; implementation</h4><div class="discipline-stack">${detail.stack.map(([name,context])=>`<div><span class="stack-marker" aria-hidden="true"><img src="assets/tech-icons/${expertiseIcons[name]||'cicd'}.svg" alt=""></span><span><strong>${name}</strong><small>${context}</small></span></div>`).join('')}</div><h4 class="discipline-label">Core focus &amp; evidence</h4><ul class="discipline-evidence">${x.evidence.map(e=>`<li>${e}</li>`).join('')}</ul><div class="discipline-projects"><span class="discipline-label">Related work</span>${detail.projects.map(slug=>`<a href="projects/#${slug}">${D.projects.find(p=>p.slug===slug).name} ↗</a>`).join('')}</div><div class="discipline-contact"><span>Have an engineering opportunity?</span><a href="contact/">Get in touch ↗</a></div>`};renderExpertise('software');qa('[data-expertise]').forEach(b=>{const detail=disciplineDetails[b.dataset.expertise];const title=document.createElement('strong');title.textContent=b.textContent;const subtitle=document.createElement('small');subtitle.textContent=detail.subtitle;b.replaceChildren(title,subtitle);b.addEventListener('click',()=>{qa('[data-expertise]').forEach(x=>x.setAttribute('aria-selected','false'));b.setAttribute('aria-selected','true');renderExpertise(b.dataset.expertise)})});
const art=p=>p.image?`<img class="project-art-image project-art-image-${p.slug}" src="${p.image}" alt="${p.name} architecture or product preview">`:`<span class="type-art">${p.name}</span>`;const cards=(filter='all')=>{q('#project-grid').innerHTML=D.projects.filter(p=>filter==='all'||p.tags.includes(filter)).map(p=>`<article class="project-card"><div class="project-art">${art(p)}</div><div class="project-card-body"><div class="project-eyebrow">${p.tags.join(" · ")}</div><div class="project-title-row"><h3>${p.name}</h3><button class="quick-detail" data-project="${p.slug}" aria-label="View detailed information for ${p.name}">ⓘ</button></div><p>${p.summary}</p><div class="stack-pills">${p.stack.map(s=>`<span>${s}</span>`).join("")}</div><div class="project-actions"><a class="project-primary" href="${p.live||p.proof||p.repo}" target="_blank" rel="noreferrer">${p.live?"Live site":p.proof?"View evidence":"Explore project"}</a><a href="${p.repo}" target="_blank" rel="noreferrer">Source</a></div></div></article>`).join('');qa('[data-project]').forEach(b=>b.addEventListener('click',()=>openProject(b.dataset.project)))};cards();qa('[data-filter]').forEach(b=>b.addEventListener('click',()=>{qa('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');cards(b.dataset.filter)}));
const pd=q('#project-dialog');function openProject(slug){const p=D.projects.find(x=>x.slug===slug);q('#project-dialog-content').innerHTML=`<header class="project-dialog-heading"><p class="meta">${p.role}</p><h2 id="project-dialog-title">${p.name}</h2><p class="project-dialog-summary">${p.summary}</p></header>${p.image?`<figure class="project-dialog-visual"><img src="${p.image}" alt="${p.name} architecture or product view"><figcaption>${p.name} system view</figcaption></figure>`:''}<div class="project-story-grid"><section class="project-story-problem"><span class="detail-index">01</span><h3>The real problem</h3><p>${p.problem}</p></section><section><span class="detail-index">02</span><h3>Who it helps</h3><p>${p.audience}</p></section><section><span class="detail-index">03</span><h3>How the system responds</h3><p>${p.solution}</p></section><section><span class="detail-index">04</span><h3>What I built</h3><p>${p.contribution}</p></section></div><div class="project-detail-lower"><section><h3>Core capabilities</h3><ul class="capability-list">${p.capabilities.map(e=>`<li>${e}</li>`).join('')}</ul></section><section><h3>Evidence</h3><ul>${p.evidence.map(e=>`<li>${e}</li>`).join('')}</ul></section><section><h3>Technology</h3><div class="stack-pills">${p.stack.map(s=>`<span>${s}</span>`).join('')}</div></section></div><div class="project-actions"><a href="${p.repo}" target="_blank" rel="noreferrer">View source</a>${p.proof?`<a href="${p.proof}" target="_blank" rel="noreferrer">External evidence</a>`:''}${p.live?`<a class="project-primary" href="${p.live}" target="_blank" rel="noreferrer">Open live project</a>`:''}</div>`;pd.showModal()}
qa('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));qa('dialog').forEach(d=>d.addEventListener('click',e=>{const r=d.getBoundingClientRect();if(e.target===d&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))d.close()}));
const nav=q('.pill-nav'),menu=q('.menu-toggle');menu.addEventListener('click',()=>{const o=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(o))});qa('.pill-nav a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));
const terminal=q('#terminal-dialog'),chat=q('#chat-dialog');qa('[data-open]').forEach(b=>{const isTerminal=b.dataset.open==='terminal',d=isTerminal?terminal:chat;b.setAttribute('aria-controls',d.id);b.setAttribute('aria-expanded','false');b.addEventListener('click',()=>{if(d.open){d.close();return}if(isTerminal){chat.close();d.showModal()}else d.show();b.setAttribute('aria-expanded','true');q(isTerminal?'#terminal-input':'#chat-input').focus()});d.addEventListener('close',()=>b.setAttribute('aria-expanded','false'))});chat.addEventListener('keydown',e=>{if(e.key==='Escape'){chat.close();q('[data-open="chat"]').focus()}});
const termOut=q('#terminal-output'),termForm=q('#terminal-form'),termInput=q('#terminal-input');const links={github:'https://github.com/ritiksah141',linkedin:'https://www.linkedin.com/in/ritik-sah-858015335/',resume:'resume/',contact:'contact/'};const cmds={help:'Commands: about, projects, project <name>, skills, experience, education, proof, resume, github, linkedin, contact, clear, matrix, stop, theme [matrix|amber|ice], neofetch',about:'Ritik Sah is a London-based Computing Systems undergraduate and software engineer working across cloud, full-stack, AI-assisted and security-focused products.',projects:'OpenShield · DUSK · IoTSentinel · BreachLens · ThreatVault. Use project <name> for details.',skills:'Python · Java · SQL · Flask · Angular 17 · Azure · Docker · Linux · PostgreSQL · MongoDB · GitHub Actions · Zeek · River ML',experience:'Database Administrator, Arunima Secondary School, Dec 2020 to Jul 2022. Current engineering evidence is represented through open-source and project work.',education:'BSc (Hons) Computing Systems with Diploma in Professional Practice, Ulster University London. Dean’s Award recipient in Years 1 and 2. QAHE TechFest 2026 winner.',proof:'OpenShield public maintainer record · DUSK in Superlinked SIE · 1,263 IoTSentinel tests · 889 BreachLens tests.'};
const writeTerminal=(text,className='terminal-response')=>{const row=document.createElement('p');row.className=className;row.textContent=text;termOut.append(row);return row};
const writePrompt=command=>{const row=document.createElement('p');row.className='terminal-command-line';const prompt=document.createElement('span');prompt.className='terminal-prompt';prompt.textContent='visitor@portfolio:~$';const value=document.createElement('span');value.className='terminal-command';value.textContent=command;row.append(prompt,' ',value);termOut.append(row)};
termForm.addEventListener('submit',e=>{e.preventDefault();const raw=termInput.value.trim(),low=raw.toLowerCase();if(low==='clear'){termOut.innerHTML='';termInput.value='';return}writePrompt(raw);if(low.startsWith('project ')){const name=low.slice(8).replace(/\s/g,'');const p=D.projects.find(x=>x.slug===name||x.name.toLowerCase().replace(/\s/g,'')===name);const row=writeTerminal(p?p.summary:'Project not found. Type projects to list valid names.',p?'terminal-response':'terminal-error');if(p){const title=document.createElement('b');title.textContent=p.name+' — ';row.prepend(title)}}else if(links[low]){const row=writeTerminal('Open ','terminal-response');const anchor=document.createElement('a');anchor.href=links[low];anchor.textContent=low;if(low==='github'||low==='linkedin'){anchor.target='_blank';anchor.rel='noreferrer'}row.append(anchor,'.')}else writeTerminal(cmds[low]||'bash: command not found. Type help to list available commands.',cmds[low]?'terminal-response':'terminal-error');termInput.value='';termOut.scrollTop=termOut.scrollHeight});
const chatForm=q('#chat-form'),chatInput=q('#chat-input'),messages=q('#chat-messages');
function answer(text){
  const t=text.toLowerCase().replace(/[^a-z0-9+#.\s-]/g,' ');
  const projectLinks=p=>[[p.name+' source',p.repo],...(p.proof?[['External evidence',p.proof]]:[]),...(p.live?[['Live project',p.live]]:[])];
  const named=D.projects.filter(p=>t.includes(p.name.toLowerCase())||t.includes(p.slug));
  if(/sponsor|visa|work author|salary|citizenship|passport|home address|phone number|age|date of birth/.test(t))return {text:'That personal or employment-eligibility information is not published on this site. Ritik can confirm it directly for a specific opportunity.',links:[['Contact Ritik','contact/']]};
  if(named.length===1){const p=named[0];if(/problem|solve|why|purpose|use case/.test(t))return {text:`${p.name} addresses this problem: ${p.problem}`,links:projectLinks(p)};if(/who|user|audience|help/.test(t))return {text:`${p.name} is designed for ${p.audience.charAt(0).toLowerCase()+p.audience.slice(1)}`,links:projectLinks(p)};if(/how|architecture|design|work|approach/.test(t))return {text:`${p.name}: ${p.solution}`,links:projectLinks(p)};if(/evidence|test|proof|result|metric/.test(t))return {text:`Evidence recorded for ${p.name}: ${p.evidence.join('; ')}.`,links:projectLinks(p)};if(/stack|technology|built with|language/.test(t))return {text:`${p.name} uses ${p.stack.join(', ')}.`,links:projectLinks(p)};return {text:`${p.name}: ${p.summary} ${p.problem} The system response is: ${p.solution}`,links:projectLinks(p)};}
  if(named.length>1||/compare|difference|versus| vs /.test(t)){const selected=named.length?named:D.projects.slice(0,3);return {text:selected.map(p=>`${p.name} solves ${p.problem}`).join(' '),links:selected.map(p=>[p.name,p.live||p.proof||p.repo])};}
  if(/who (is|s) ritik|about ritik|tell me about|introduction|profile/.test(t))return {text:'Ritik Sah is a London-based Computing Systems undergraduate and software engineer building full-stack, cloud and security-focused systems. His public evidence includes OWASP OpenShield maintenance, the DUSK Superlinked integration and five portfolio projects.',links:[['Read resume','resume/'],['View projects','projects/']]};
  if(/open.?source|maintainer|owasp|superlinked|contribution/.test(t))return {text:'Ritik is listed as OpenShield’s API and AI maintainer. DUSK is also published in Superlinked SIE as the agent-action-monitor example, providing external evidence of collaborative engineering work.',links:[['OpenShield maintainer record',D.projects[0].proof],['Superlinked integration',D.projects[1].proof]]};
  if(/live|demo|website|deployed|try/.test(t))return {text:'The publicly linked live products are IoTSentinel and BreachLens. Other projects link to their source or external contribution evidence.',links:D.projects.filter(p=>p.live).map(p=>[p.name+' live',p.live])};
  if(/azure|cloud|logic app|key vault|cosmos|blob/.test(t))return {text:'OpenShield and ThreatVault demonstrate Azure engineering. ThreatVault uses 19 Logic App workflows with Blob Storage, Azure SQL, Cosmos DB and Key Vault; OpenShield scans Azure posture through a Python/Flask platform.',links:[['OpenShield',D.projects[0].repo],['ThreatVault',D.projects[4].repo]]};
  if(/front.?end|angular|react|interface|ui|dashboard/.test(t))return {text:'The portfolio shows Angular 17 in BreachLens, React/Vite integration in OpenShield, dashboard and investigation interfaces in IoTSentinel, and a static Azure-hosted interface in ThreatVault.',links:[['BreachLens live',D.projects[3].live],['Project archive','projects/']]};
  if(/back.?end|api|flask|database|data|sql|mongo|postgres/.test(t))return {text:'Ritik’s backend work includes Python and Flask APIs, REST boundaries, PostgreSQL, MongoDB, Azure SQL, Cosmos DB and SQLite. BreachLens exposes 65 REST endpoints, while OpenShield and DUSK add PostgreSQL-backed platform work.',links:[['Project archive','projects/'],['Read resume','resume/']]};
  if(/security|secure|threat|privacy|risk/.test(t))return {text:'Security work spans cloud posture in OpenShield, AI-agent behaviour in DUSK, private network monitoring in IoTSentinel, privacy-aware breach queries in BreachLens and controlled evidence handling in ThreatVault.',links:[['Security projects','projects/']]};
  if(/ai|machine learning|ml|llm|ollama|agent/.test(t))return {text:'AI-related work includes behavioural controls for AI agents in DUSK, local Ollama-first explanations and River online learning in IoTSentinel, AI-assisted work in OpenShield, and Azure Content Safety in ThreatVault.',links:[['DUSK source',D.projects[1].repo],['IoTSentinel',D.projects[2].live]]};
  if(/test|quality|ci|reliable|verification/.test(t))return {text:'Ritik treats tests and delivery gates as engineering evidence: the portfolio records 1,263 IoTSentinel tests, 889 BreachLens tests, OpenShield CI quality gates and benchmark validation for DUSK.',links:[['Project archive','projects/']]};
  if(/skill|stack|technology|technologies|language|tool/.test(t))return {text:'Core technologies shown here include Python, Java, SQL, Flask, Angular 17, React, Azure, Docker, Linux, PostgreSQL, MongoDB, GitHub Actions, Zeek, River ML and Ollama.',links:[['Skills and experience','resume/']]};
  if(/experience|employment|job|career|role/.test(t))return {text:'Ritik worked as a Database Administrator at Arunima Secondary School from December 2020 to July 2022. His current engineering evidence comes from open-source responsibility and software, cloud and security projects. He is targeting graduate software, cloud and platform roles.',links:[['Read resume','resume/'],['Contact Ritik','contact/']]};
  if(/education|university|degree|student|award|techfest|dean/.test(t))return {text:'Ritik studies BSc (Hons) Computing Systems with Diploma in Professional Practice at Ulster University London. The site records Dean’s Award recognition in Years 1 and 2 and a QAHE TechFest 2026 Project Showcase and Poster Exhibition win.',links:[['Education and recognition','resume/']]};
  if(/journey|background|started|path/.test(t))return {text:'Ritik’s path moves from database operations into Computing Systems, then into open-source cloud and AI-security delivery, followed by public project recognition. The Journey section presents those four phases.',links:[['View Journey','#journey']]};
  if(/process|lifecycle|design approach|method|how does ritik build/.test(t))return {text:'Ritik’s engineering lifecycle is: discover and frame, design boundaries, build for change, verify the system, then operate and evolve. Runtime evidence feeds the next iteration.',links:[['View lifecycle','#workflow']]};
  if(/contact|email|linkedin|reach|hire/.test(t))return {text:'Email Ritik at ritiksah141@gmail.com or connect through LinkedIn. The contact page collects all public contact options.',links:[['Contact options','contact/'],['LinkedIn','https://www.linkedin.com/in/ritik-sah-858015335/']]};
  if(/resume|cv/.test(t))return {text:'Ritik’s public resume is available as an accessible web page and a downloadable PDF.',links:[['Read resume','resume/'],['Download PDF','assets/Ritik_Sah_Public_Resume.pdf']]};
  if(/github|code|repository|repositories|source/.test(t))return {text:'Ritik’s public GitHub profile and each project’s source repository are linked from this site.',links:[['GitHub','https://github.com/ritiksah141'],['Project archive','projects/']]};
  if(/build|project|portfolio|work|solve/.test(t))return {text:'Ritik builds systems around five practical problems: Azure posture risk, unsafe AI-agent actions, opaque IoT behaviour, fragmented breach intelligence and controlled digital-evidence handling.',links:[['Explore all projects','projects/']]};
  const stop=new Set(['what','which','where','when','why','how','does','did','can','could','would','about','tell','show','give','with','from','that','this','have','has','the','and','for','his','ritik','site']);
  const terms=t.split(/\s+/).filter(x=>x.length>2&&!stop.has(x));
  const ranked=D.projects.map(p=>({p,score:terms.reduce((n,term)=>n+([p.name,p.summary,p.problem,p.audience,p.solution,p.contribution,...p.capabilities,...p.evidence,...p.stack,...p.tags].join(' ').toLowerCase().includes(term)?1:0),0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score);
  if(ranked.length){const matches=ranked.slice(0,2).map(x=>x.p);return {text:`The closest portfolio evidence is ${matches.map(p=>p.name).join(' and ')}. ${matches.map(p=>p.summary).join(' ')}`,links:matches.map(p=>[p.name,p.live||p.proof||p.repo])};}
  return {text:'I can answer questions about Ritik’s projects, architecture, technologies, problem-solving approach, experience, education, awards, open-source evidence, resume and contact details. That specific fact is not published, so Ritik would need to answer it directly.',links:[['Ask Ritik directly','contact/']]};
}
function send(text){
  if(!text.trim())return;
  const user=document.createElement('div');user.className='user';user.textContent=text.slice(0,2000);
  const reply=answer(text),bot=document.createElement('div');bot.className='bot';
  const body=document.createElement('p');body.textContent=reply.text;bot.append(body);
  const sources=document.createElement('div');sources.className='answer-sources';
  reply.links.forEach(([label,url])=>{const a=document.createElement('a');a.textContent=label;a.href=url;if(url.startsWith('https:')){a.target='_blank';a.rel='noreferrer';}sources.append(a);});
  bot.append(sources);messages.append(user,bot);messages.scrollTop=messages.scrollHeight;
}
chatForm.addEventListener('submit',e=>{e.preventDefault();send(chatInput.value);chatInput.value=''});
qa('#prompt-row button').forEach(b=>b.addEventListener('click',()=>send(b.textContent)));
q('#year').textContent=new Date().getFullYear();const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){const id=e.target.id;qa('.pill-nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${id}`))}}),{rootMargin:'-45% 0px -45%'});qa('main section[id]').forEach(s=>obs.observe(s));})();
